# Generated by Django 5.1.2 on 2024-10-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
